name: continuous integration

on:
  pull_request:
    branches:
      - 'main'

permissions:
  checks: write
  contents: write
  pages: write
  deployments: write
  pull-requests: write

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Test with Gradle
        run: ./gradlew test

      - name: Report Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml

      - name: Upload Jacoco Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
